"""AquaSavannah LandVault — Contract Package.

This package is the **immutable platform contract** for the application.
The contents of `contracts/v1/` are governed artifacts and MUST NOT be
edited by hand — they are regenerated by `python -m contracts.generate`
and validated by `tests/test_contract_freeze.py`.

See `/app/contracts/CHANGELOG.md` and
`/app/contracts/v1/adr/ADR-0001-platform-contract-freeze.md`.
"""
