"""Port: session persistence (Identity context)."""
from __future__ import annotations

from typing import Optional, Protocol

from contexts.identity.domain.session import Session


class SessionRepositoryPort(Protocol):
    async def add(self, session: Session) -> Session: ...
    async def get(self, session_id: str) -> Optional[Session]: ...
    async def get_by_refresh_hash(self, refresh_hash: str) -> Optional[Session]: ...
    async def revoke(self, session_id: str, reason: str) -> None: ...
    async def revoke_user_sessions(self, user_id: str, reason: str) -> int: ...
